spring.application.name=portfolio-api

# ===============================
# SERVEUR
# ===============================
server.port=8080

# ===============================
# POSTGRESQL
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# GITHUB
# ===============================
github.api.base-url=https://api.github.com
github.api.username=laeti-challant
github.api.token=${GITHUB_TOKEN}

# ===============================
# CACHE
# ===============================
spring.cache.type=simple

# ===============================
# MAIL (SMTP Gmail)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.recipient=${MAIL_RECIPIENT:l.challant@gmail.com}
